### PR TITLE
Feature/personal account manager

### PR DESCRIPTION
**Pull request by JiMeow**
Still have problems with lint (dependency in useEffect on `src\modules\admin\account\EditPassword.tsx` and `src\modules\admin\account\EditUsername.tsx`)

P.S.
*Please check that PR is work according to design or not, I have been checking everything but still not sure about it
*Please remind me about axiosError.message

### CODE REVIEW

**Review by GolfGrab — CHANGES_REQUESTED** [review]
pls remove all placeholder

**Comment by JiMeow** [comment]
> pls remove all placeholder

Resolve

**Comment by GolfGrab** [comment]
image

pls investigate this bug @JiMeow

**Comment by GolfGrab** [comment]
image
a lot of bug 😴

**Comment by GolfGrab** [comment]
image

**Review by GolfGrab — APPROVED** [review]
nice

**Pull request merged**
